version: '3.8'

services:
  orchestrator:
    build: .
    environment:
      - MIN_EV_NATIVE=0.005
    volumes:
      - ../configs:/app/configs
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
