chains:
  base:
    rpc: "https://mainnet.base.org"
    chain_id: 8453
    native_token: "ETH"
    block_time: 2
    
  arbitrum:
    rpc: "https://arb1.arbitrum.io/rpc"
    chain_id: 42161
    native_token: "ETH"
    block_time: 0.25
    
  ethereum:
    rpc: "https://eth.llamarpc.com"
    chain_id: 1
    native_token: "ETH"
    block_time: 12
